In [1]:
import tensorflow as tf

2024-04-09 20:18:33.798938: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-09 20:18:33.820336: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-09 20:18:34.161054: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
aa = tf.constant(1.2)

2024-04-09 20:18:50.188983: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-09 20:18:50.189100: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-09 20:18:50.210400: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [3]:
aa

<tf.Tensor: shape=(), dtype=float32, numpy=1.2>

In [4]:
a = tf.constant([[1,2],[3,4]])

In [5]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.cast(a, tf.float32)

In [6]:
a = tf.constant([-1, 0, 1, 2]) # 创建 TF 张量
aa = tf.Variable(a) # 转换为 Variable 类型


In [ ]:
tf.zeros([2,3])

In [ ]:
tf.ones_like(a)

In [7]:
# 创建一个形状为 [2,3] 的张量，元素值全为 99
tf.fill([2,2], 99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

In [8]:
tf.random.normal([2,2], mean=1,stddev=2) # 创建正态分布的张量

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1000173,  1.6489086],
       [ 0.8836016,  1.1149076]], dtype=float32)>

In [9]:
tf.random.uniform([2,2],maxval=10) # 创建采样自[0,10)均匀分布的矩阵

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.3443003, 8.611906 ],
       [2.2163522, 2.2956932]], dtype=float32)>

In [10]:
tf.range(10) # 0~10，不包含 10

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [13]:
from tensorflow import keras

In [15]:
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb.npz: None -- [Errno 104] Connection reset by peer

In [16]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1,  0,  1,  2], dtype=int32)>

In [18]:
a[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [20]:
 a[0,::]

2024-04-09 20:43:13.065857: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at strided_slice_op.cc:117 : INVALID_ARGUMENT: Index out of range using input dim 1; input has only 1 dims


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Index out of range using input dim 1; input has only 1 dims [Op:StridedSlice] name: strided_slice/

In [21]:
x = tf.range(96)

In [22]:
x=tf.reshape(x,[2,4,4,3])

In [23]:
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [24]:
tf.reshape(x,[2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [25]:
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)

In [26]:
x.shape

TensorShape([28, 28])

In [27]:
x = tf.expand_dims(x,axis=2) # axis=2 表示宽维度后面的一个维度 

In [31]:
x.shape

TensorShape([1, 28, 28, 1])

In [30]:
 x = tf.expand_dims(x,axis=0) # 高维度之前插入新维度

In [32]:
tf.transpose(x,perm=[0,3,2,1]) # 交换维度

<tf.Tensor: shape=(1, 1, 28, 28), dtype=int32, numpy=
array([[[[2, 0, 3, 3, 9, 6, 6, 1, 2, 8, 5, 5, 5, 8, 0, 8, 5, 9, 4, 9,
          2, 7, 6, 1, 2, 7, 5, 4],
         [6, 2, 5, 4, 4, 2, 3, 1, 6, 2, 3, 5, 0, 5, 1, 9, 2, 2, 9, 1,
          1, 3, 1, 4, 8, 1, 9, 5],
         [8, 8, 4, 2, 1, 0, 3, 2, 2, 6, 8, 7, 6, 0, 8, 2, 3, 8, 0, 7,
          8, 4, 8, 5, 2, 4, 3, 3],
         [3, 6, 5, 4, 6, 2, 8, 6, 3, 1, 4, 3, 0, 9, 8, 6, 9, 8, 9, 9,
          9, 3, 6, 9, 3, 1, 6, 1],
         [6, 9, 0, 2, 3, 2, 6, 5, 0, 5, 4, 5, 4, 7, 0, 1, 2, 7, 3, 8,
          3, 0, 4, 9, 6, 8, 8, 1],
         [9, 0, 9, 2, 3, 4, 2, 7, 1, 8, 1, 2, 9, 0, 6, 1, 3, 8, 7, 4,
          4, 0, 4, 0, 1, 4, 4, 3],
         [4, 6, 7, 8, 4, 9, 9, 2, 3, 3, 4, 5, 6, 0, 2, 3, 6, 2, 4, 9,
          2, 0, 8, 8, 9, 0, 6, 4],
         [4, 5, 0, 3, 8, 3, 4, 2, 8, 8, 7, 3, 4, 9, 7, 9, 8, 8, 4, 2,
          0, 0, 4, 6, 9, 0, 1, 7],
         [1, 2, 1, 8, 7, 1, 4, 8, 0, 2, 7, 9, 3, 6, 5, 7, 7, 8, 1, 1,
          8, 2, 8, 7, 3, 6, 8, 3],
 

In [ ]:
b = tf.constant([1,2]) # 创建向量 b
b = tf.expand_dims(b, axis=0) # 插入新维度，变成矩阵


In [33]:
x = tf.random.normal([2,4])
w = tf.random.normal([4,3])

In [34]:
b = tf.random.normal([3])
y = x@w+b # 不同 shape 的张量直接相加

2024-04-09 21:10:28.061517: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [35]:
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.61850816,  1.0880204 , -2.3115153 ],
       [ 1.8540735 , -4.17789   ,  0.99293435]], dtype=float32)>

In [36]:
a = tf.range(5)
b = tf.constant(2)
a//b # 整除运算

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2], dtype=int32)>

In [40]:
tf.math.log(tf.constant(10))

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [42]:
tf.math.log(tf.constant(10, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>

In [43]:
x = tf.random.normal([10,35,8])

In [44]:
result = tf.split(x, num_or_size_splits=10, axis=0)

In [45]:
len(result)

10

In [46]:
a = tf.constant([[1,2],[3,4]])

In [ ]:
# 将a 转换为0,1矩阵，大于0的元素变为1，否则变为0
tf.cast(a>0, dtype=tf.int32)



In [48]:
tf.reduce_sum(a, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [49]:
tf.divide(a,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [53]:
tf.expand_dims(a, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [55]:
a = tf.range(5)

In [56]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [57]:
tf.transpose(a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [58]:
a = tf.random.normal([5,5])

In [59]:
a

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-3.3011556 ,  0.03138566, -1.6656014 ,  0.07812436,  1.9093177 ],
       [-2.5646603 ,  0.86610556,  0.59160936, -0.67044526, -1.314558  ],
       [-1.176601  , -0.6477645 , -0.21941549, -0.01605961,  0.33417445],
       [-0.76610345,  2.073915  , -0.8777282 , -1.3523014 ,  1.0532312 ],
       [-0.52562267, -0.39263606, -1.2021484 , -1.4939462 ,  0.42307222]],
      dtype=float32)>

In [60]:
a[0,:]

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-3.3011556 ,  0.03138566, -1.6656014 ,  0.07812436,  1.9093177 ],
      dtype=float32)>

In [61]:
row_i = a[0,:]

In [62]:
row_j = a[1, :]

In [63]:
row_j_transpose = tf.transpose(row_j)

In [64]:
support_ij = tf.matmul(row_i, row_j_transpose) / C

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:GPU:0}} In[0] and In[1] ndims must be == 2: 1 [Op:MatMul] name: 

In [65]:
row_i

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-3.3011556 ,  0.03138566, -1.6656014 ,  0.07812436,  1.9093177 ],
      dtype=float32)>

In [66]:
row_j_transpose

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-2.5646603 ,  0.86610556,  0.59160936, -0.67044526, -1.314558  ],
      dtype=float32)>

In [67]:
tf.transpose(row_j)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-2.5646603 ,  0.86610556,  0.59160936, -0.67044526, -1.314558  ],
      dtype=float32)>

In [70]:
row_i = tf.expand_dims(row_i, axis=0)

In [71]:
row_j_transpose = tf.expand_dims(row_j, axis=1)

In [72]:
row_i

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-3.3011556 ,  0.03138566, -1.6656014 ,  0.07812436,  1.9093177 ]],
      dtype=float32)>

In [74]:
row_j_transpose

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[-2.5646603 ],
       [ 0.86610556],
       [ 0.59160936],
       [-0.67044526],
       [-1.314558  ]], dtype=float32)>

In [76]:
support_ij = tf.matmul(row_i, row_j_transpose) / 5

In [77]:
support_ij

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.98917085]], dtype=float32)>

In [78]:
a.shape[1]

5

In [80]:
# 多个基因的支持度
def support_multi(data, i, j):
    # 获取self.data 的列数
    C = data.shape[1]

    # 提取self.data 的第i行和第j行
    row_i = data[i, :]
    # 将row_i 转置为 1行 n列的张量
    row_i = tf.expand_dims(row_i, axis=0)

    row_j = data[j, :]
    # 将row_j 转置为 n行 1列的张量
    row_j_transpose = tf.expand_dims(row_j, axis=1)

    # 计算两个矩阵的矩阵乘积，即为 i 和 j 的支持度
    support_ij = tf.matmul(row_i, row_j_transpose) / C
    return support_ij

In [81]:
support_multi(a, 0, 1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.98917085]], dtype=float32)>

In [82]:
one = tf.constant(1, dtype=tf.float32)
zero = tf.constant(0, dtype=tf.float32)

In [83]:
tf.divide(one, zero)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [2]:
import tensorflow as tf

2024-04-11 22:40:55.228822: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-11 22:40:55.249589: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-11 22:40:55.580907: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
a = tf.constant([True, False])

2024-04-11 22:41:01.300722: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 22:41:01.300823: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 22:41:01.314955: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [4]:
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [5]:
tf.divide(a, tf.constant(1.2))

TypeError: `x` and `y` must have the same dtype, got tf.bool != tf.float32.